backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "stories"
    label: "Stories"
    folder: "_stories"
    create: true
    fields:
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }

  - name: "services"
    label: "Services"
    folder: "_services"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "body", widget: "text" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Cost", name: "cost", widget: "string" }
